version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: pixelart-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pixelart-network
    environment:
      - MONGO_INITDB_DATABASE=pixelart_db

  api:
    build: .
    container_name: pixelart-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - image_data:/app/images:rw
    networks:
      - pixelart-network
    environment:
      - MONGODB_URL=${MONGODB_URL:-mongodb://mongodb:27017}
      - MONGODB_DB_NAME=pixelart_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_CLOUDINARY=${USE_CLOUDINARY:-False}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - mongodb
    # Usar el start.sh que ya tienes definido en el Dockerfile
    # No sobrescribir con un command aquí

networks:
  pixelart-network:
    driver: bridge

volumes:
  mongodb_data:
  image_data: